### PR TITLE
Fix TS ignores

### LINKED ISSUE #224: [bug] [typescript] Projects using @klasa/core do not compile
Due to the main code having some `// @ts-ignore` comments which are not carried over to the build `.d.ts` files, projects currently using TypeScript and `@klasa/core` do not compile. Trying to compile a project that is basically the ping example from the readme (sample repo: https://bitbucket.org/Favna/klasa-core-test/) gives the following errors:

```
$ tsc -b src
node_modules/@klasa/core/dist/src/lib/pieces/base/Store.d.ts:71:5 - error TS2416: Property 'set' in type 'Store<V>' is not assignable to the same property in base type 'Cache<string, V>'.
  Type '(piece: V) => V | null' is not assignable to type '(key: string, value: V) => this'.
    Types of parameters 'piece' and 'key' are incompatible.
      Type 'string' is not assignable to type 'V'.
        'V' could be instantiated with an arbitrary type which could be unrelated to 'string'.

71     set(piece: V): V | null;
       ~~~

node_modules/@klasa/core/dist/src/lib/caching/stores/GuildEmojiStore.d.ts:57:15 - error TS2416: Property '_add' in type 'GuildEmojiStore' is not assignable to the same property in base type 'DataStore<GuildEmoji>'.
  Type '(data: APIEmojiData) => GuildEmoji' is not assignable to type '(data: { [k: string]: any; id: string; }) => GuildEmoji'.
    Types of parameters 'data' and 'data' are incompatible.
      Property 'name' is missing in type '{ [k: string]: any; id: string; }' but required in type 'APIEmojiData'.

57     protected _add(data: APIEmojiData): GuildEmoji;
                 ~~~~

  node_modules/@klasa/dapi-types/dist/index.d.ts:231:5
    231     name: string | null;
            ~~~~
    'name' is declared here.

node_modules/@klasa/core/dist/src/lib/caching/stores/GuildInviteStore.d.ts:43:15 - error TS2416: Property '_add' in type 'GuildInviteStore' is not assignable to the same property in base type 'DataStore<Invite>'.
  Type '(data: APIInviteData) => Invite' is not assignable to type '(data: { [k: string]: any; id: string; }) => Invite'.
    Types of parameters 'data' and 'data' are incompatible.
      Type '{ [k: string]: any; id: string; }' is missing the following properties from type 'APIInviteData': code, channel

43     protected _add(data: APIInviteData): Invite;
                 ~~~~

node_modules/@klasa/core/dist/src/lib/caching/stores/GuildMemberStore.d.ts:69:15 - error TS2416: Property '_add' in type 'GuildMemberStore' is not assignable to the same property in base type 'DataStore<GuildMember>'.
  Type '(data: MemberData) => GuildMember' is not assignable to type '(data: { [k: string]: any; id: string; }) => GuildMember'.
    Types of parameters 'data' and 'data' are incompatible.
      Type '{ [k: string]: any; id: string; }' is not assignable to type 'MemberData'.
        Type '{ [k: string]: any; id: string; }' is missing the following properties from type 'APIGuildMemberData': nick, roles, joined_at, deaf, mute

69     protected _add(data: MemberData): GuildMember;
                 ~~~~

node_modules/@klasa/core/dist/src/lib/caching/stores/PresenceStore.d.ts:27:15 - error TS2416: Property '_add' in type 'PresenceStore' is not assignable to the same property in base type 'DataStore<Presence>'.
  Type '(data: APIPresenceUpdateData) => Presence' is not assignable to type '(data: { [k: string]: any; id: string; }) => Presence'.
    Types of parameters 'data' and 'data' are incompatible.
      Property 'user' is missing in type '{ [k: string]: any; id: string; }' but required in type 'APIPresenceUpdateData'.

27     protected _add(data: APIPresenceUpdateData): Presence;
                 ~~~~

  node_modules/@klasa/dapi-types/dist/index.d.ts:490:5
    490     user: {
            ~~~~
    'user' is declared here.

node_modules/@klasa/core/dist/src/lib/caching/stores/VoiceStateStore.d.ts:27:15 - error TS2416: Property '_add' in type 'VoiceStateStore' is not assignable to the same property in base type 'DataStore<VoiceState>'.
  Type '(data: APIVoiceStatePartial) => VoiceState' is not assignable to type '(data: { [k: string]: any; id: string; }) => VoiceState'.
    Types of parameters 'data' and 'data' are incompatible.
      Type '{ [k: string]: any; id: string; }' is missing the following properties from type 'APIVoiceStatePartial': channel_id, user_id, session_id, deaf, and 4 more.

27     protected _add(data: APIVoiceStatePartial): VoiceState;
                 ~~~~

node_modules/@klasa/core/dist/src/lib/caching/stores/InviteStore.d.ts:37:15 - error TS2416: Property '_add' in type 'InviteStore' is not assignable to the same property in base type 'DataStore<Invite>'.
  Type '(data: APIInviteData) => Invite' is not assignable to type '(data: { [k: string]: any; id: string; }) => Invite'.
    Types of parameters 'data' and 'data' are incompatible.
      Type '{ [k: string]: any; id: string; }' is not assignable to type 'APIInviteData'.

37     protected _add(data: APIInviteData): Invite;
                 ~~~~

node_modules/@klasa/core/dist/src/lib/caching/stores/BanStore.d.ts:83:15 - error TS2416: Property '_add' in type 'BanStore' is not assignable to the same property in base type 'DataStore<Ban>'.
  Type '(data: { guild_id: string; user: APIUserData; }) => Ban' is not assignable to type '(data: { [k: string]: any; id: string; }) => Ban'.
    Types of parameters 'data' and 'data' are incompatible.
      Type '{ [k: string]: any; id: string; }' is missing the following properties from type '{ guild_id: string; user: APIUserData; }': guild_id, user

83     protected _add(data: GuildBanAddDispatch['d']): Ban;
                 ~~~~


Found 8 errors.

error Command failed with exit code 1.
```

Taking a closer look at the top one:
```
node_modules/@klasa/core/dist/src/lib/pieces/base/Store.d.ts:71:5 - error TS2416: Property 'set' in type 'Store<V>' is not assignable to the same property in base type 'Cache<string, V>'.
  Type '(piece: V) => V | null' is not assignable to type '(key: string, value: V) => this'.
    Types of parameters 'piece' and 'key' are incompatible.
      Type 'string' is not assignable to type 'V'.
        'V' could be instantiated with an arbitrary type which could be unrelated to 'string'.

71     set(piece: V): V | null;
       ~~~
```

This code in the source is, with a `// @ts-ignore` comment.
https://github.com/dirigeants/core/blob/a82ce4160b982df9d7c3d33f30ef49ae30afe357/src/lib/pieces/base/Store.ts#L117-L128

However the code that's in `dist/src/lib/pieces/base/Store.d.ts` does not (full file: https://unpkg.com/browse/@klasa/core@0.0.2/dist/src/lib/pieces/base/Store.d.ts):
```

/**
--
67 | * Sets up a piece in our store.
68 | * @since 0.0.1
69 | * @param piece The piece we are setting up
70 | */
71 | set(piece: V): V \| null;
```

That said, currently the only way for TypeScript users to use @klasa/core is by setting `skipLibCheck` to `true` in their tsconfig's. This is far from ideal and it would be better if these tsignore's can be resolved in the main code so they are no longer required.

### PR DESCRIPTION
**Pull request by PyroTechniac**
This should fix #224

### CODE REVIEW

File: src/lib/pieces/base/Store.ts [hunk 1]
```diff
@@ -137,18 +135,34 @@ export class Store<V extends Piece> extends Cache<string, V> {
...
+	 */
+	public set(): never {
+		throw new Error('Cannot set in this Store.');
+	}
+
+	/**
+	 * The overriden delete method, this will always throw.
+	 * @internal
+	 */
+	public delete(): never {
```
Comment (vladfrangu) [inline src/lib/pieces/base/Store.ts:162]: q: Can't we just keep delete as an alias?
